apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-writer
  namespace: f1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-writer
  template:
    metadata:
      labels:
        app: redis-writer
    spec:
      containers:
        - name: redis-writer
          image: asia-south1-docker.pkg.dev/strat-project19/f1-repo/redis-writer:v2
          ports:
            - containerPort: 8001
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "pkc-41p56.asia-south1.gcp.confluent.cloud:9092"
            - name: KAFKA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: api-key
            - name: KAFKA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: api-secret
            - name: REDIS_HOST
              value: "10.155.35.4"
            - name: REDIS_PORT
              value: "6379"